### ISSUE TITLE
Can't build transaction

### ISSUE THREAD

**Issue by oggy95** [stratisproject/StratisFullNode#183]
Hello. Trying to build transaction and got an error:

```
fail: Stratis.Bitcoin.Features.Wallet.Controllers.WalletController[0]
      Exception occurred: System.ArgumentNullException: Value cannot be null. (Parameter 'key')
         at Microsoft.Extensions.Caching.Memory.MemoryCache.ValidateCacheKey(Object key)
         at Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(Object key, Object& result)
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
         at Stratis.Bitcoin.Features.Wallet.WalletManager.GetExtKey(WalletAccountReference accountReference, String password) in /root/StratisFullNode/src/Stratis.Bitcoin.Features$
Wallet/WalletManager.cs:line 1306
         at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.AddSecrets(TransactionBuildContext context, IEnumerable`1 coinsSpent) in /root/StratisFullNode/src/Stratis.Bit$
oin.Features.Wallet/WalletTransactionHandler.cs:line 257
         at Stratis.Bitcoin.Features.Wallet.WalletTransactionHandler.BuildTransaction(TransactionBuildContext context) in /root/StratisFullNode/src/Stratis.Bitcoin.Features.Wallet$
WalletTransactionHandler.cs:line 79
         at Stratis.Bitcoin.Features.Wallet.Services.WalletService.<>c__DisplayClass26_0.<BuildTransaction>b__0() in /root/StratisFullNode/src/Stratis.Bitcoin.Features.Wallet/Serv$
ces/WalletService.cs:line 728
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location where exception was thrown ---
         at Stratis.Bitcoin.Features.Wallet.Services.WalletService.BuildTransaction(BuildTransactionRequest request, CancellationToken cancellationToken) in /root/StratisFullNode/$
rc/Stratis.Bitcoin.Features.Wallet/Services/WalletService.cs:line 647
         at Stratis.Bitcoin.Features.Wallet.Controllers.WalletController.<BuildTransaction>b__20_0(BuildTransactionRequest req, CancellationToken token) in /root/StratisFullNode/s$
c/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs:line 413
         at Stratis.Bitcoin.Builder.Feature.FeatureControllerBase.Execute[TRequest](TRequest request, CancellationToken token, Func`3 action, Boolean checkModelState) in /root/Str$
tisFullNode/src/Stratis.Bitcoin/Builder/Feature/FeatureControllerBase.cs:line 39
```

Request body:
{
    "password": "MY_PASSWORD",
    "walletName": "WALLET_NAME",
    "feeType": "Low",
    "recipients": [{
        "destinationAddress": "RECIPIENT_ADDRESS",
        "amount": 1
    }]
}

dotnet-version 3.1.404
account restored via /api/Wallet/recover-via-extpubkey

**Comment by zeptin** [comment]
You are missing the `accountName` field I think

**Comment by oggy95** [comment]
Specified, but error still exist

**Comment by oggy95** [comment]
Created new account, refill this account from strax wallet and tried again. Works.
Account restored via /api/Wallet/recover-via-extpubkey can't build transaction, because in api doesn't mention how to build transaction for accounts like this.

**Comment by zeptin** [comment]
@oggy95, I missed the part about restoring via extpubkey in your first post. A wallet restored in this way will have no private keys, and can't be used for building transactions (although it will show the wallet balances as normal). So this is expected behaviour.
