### ISSUE TITLE
"Connected to the API. Waiting for node to initialize" > Wallet never load > Poor UX for Strax Wallet

### ISSUE THREAD

**Issue by trunghieud** [stratisproject/StratisFullNode#386]
I know many users have complain about this issue in Telegram and Discord. They don't check Task Manager or the logs and their experience with Stratis and Strax wallet leaves a bad taste. I highly recommend this be fixed.

In my particular case today, I had Windows Update and the system restarted by itself. I came back home and cannot start Strax wallet. I had to delete all folders and resync. 

Problem: Starting wallet and doesn't load pass "Connected to the API. Waiting for node to initialize." 

Symptoms:
1. Wallet never load.
2. Task Manager - processes are separated. 
![TaskManager_Strax_NotLoading](https://user-images.githubusercontent.com/29716420/105122689-8ac43300-5a8b-11eb-93f7-def861bf1c03.JPG)
![TaskManager_Strax_NotLoading_2](https://user-images.githubusercontent.com/29716420/105122692-8b5cc980-5a8b-11eb-9691-1da4af47eaa7.JPG)
3. Restart wallet and Stratis Daemon crashes.

Log:

[2021-01-20 03:04:19.6581 10] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.StartAsync FlushChain starting in 60 seconds.
[2021-01-20 03:04:19.7166 11] INFO: Stratis.Bitcoin.Base.BaseFeature.StartAddressManager Loading peers from : C:\Users\Hieu\AppData\Roaming\StratisNode\strax\StraxMain.
[2021-01-20 03:04:20.0762 10] INFO: Stratis.Bitcoin.Utilities.AsyncLoop.StartAsync Periodic peer flush starting in 300 seconds.
[2021-01-20 03:04:20.2830 4] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.LogAndAddException An error occurred: 'Stratis.Bitcoin.Features.BlockStore.BlockStoreException: Block store failed to recover.
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreQueue.RecoverStoreTip() in D:\a\1\s\StratisFullNode\src\Stratis.Bitcoin.Features.BlockStore\BlockStoreQueue.cs:line 424
   at Stratis.Bitcoin.Features.BlockStore.BlockStoreQueue.Initialize() in D:\a\1\s\StratisFullNode\src\Stratis.Bitcoin.Features.BlockStore\BlockStoreQueue.cs:line 205
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in D:\a\1\s\StratisFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 227
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in D:\a\1\s\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 56
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in D:\a\1\s\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 130'
[2021-01-20 03:04:20.2908 4] ERROR: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize An error occurred starting the application.

**Comment by fassadlr** [comment]
This has now been fixed in Community Test Release 1.3.1
