### ISSUE TITLE
Error in console when running straxui - loading failed in UI

### ISSUE THREAD

**Issue by James2611** [stratisproject/StratisFullNode#454]
When I run straxui on MacOS I get the loading failed problem which several people seem to have. So I tried to run it from the terminal, and I get the following more output:

```Stratis: info: Stratis.Bitcoin.FullNode[0]
      Full node initialized on StraxMain.

Stratis: 
Application starting, press Ctrl+C to cancel.


Stratis: info: Stratis.Bitcoin.FullNode[0]
      Starting node.

Stratis: info: Stratis.Bitcoin.Features.Api.ApiFeature[0]
      API starting on URL 'http://localhost:17103/'.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading finalized block height.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading chain.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Chain loaded at height 186300.

Stratis: info: Stratis.Bitcoin.AsyncWork.AsyncProvider[0]
      FlushChain starting in 60 seconds.

Stratis: info: Stratis.Bitcoin.Base.BaseFeature[0]
      Loading peers from : /Users/jamesarben/.stratisnode/strax/StraxMain.

Stratis: info: Stratis.Bitcoin.AsyncWork.AsyncProvider[0]
      Periodic peer flush starting in 300 seconds.

Stratis: fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred: 'Stratis.Bitcoin.Consensus.ConsensusException: Violation of finality on height 169295 for RewindDataIndex.
         at Stratis.Bitcoin.Features.Consensus.ProvenBlockHeaders.RewindDataIndexCache.Initialize(Int32 tipHeight, ICoinView coinView) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/ProvenBlockHeaders/RewindDataIndexCache.cs:line 66
         at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize(ChainedHeader chainTip) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 62
         at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 229
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 56
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in /Users/runner/work/1/s/StratisFullNode/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 130'

Stratis: fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application.
```

I'm not sure how to get it working from here and would appreciate any assistance and advice.

For reference, this is with the latest release (1.1.0) but also happens with the 1.2.0 community support release which I tried. I'm using MacOS 10.14.6.

**Comment by James2611** [comment]
I managed to resolve this by moving ~/.stratisnode away and starting again. Fortunately I hadn't created a wallet yet so nothing was lost.
