### ISSUE TITLE
Stratis.BitcoinD unable to restart

### ISSUE THREAD

**Issue by randalstout** [stratisproject/StratisFullNode#626]
A Windows upgrade caused a termination in Stratis.BitcoinD which will not allow the program to restart.

Errors:

        Consensus at height 310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679-HeaderValidated is ahead of the block store at height 271535-00000000000000007cd966207ee36f86cdd8a05d6578f92fe35b208dd3d97d3c-HeaderValidated, rewinding consensus.
[error] Stratis.Bitcoin.Builder.FullNodeFeatureExecutor
        An error occurred starting full node feature 'BaseFeature' : 'System.InvalidOperationException: No rewind data found for block `310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679`
           at Stratis.Bitcoin.Features.Consensus.CoinViews.LevelDbCoindb.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\Coindb\LeveldbCoindb.cs:line 202
           at Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\CachedCoinView.cs:line 622
           at Stratis.Bitcoin.Features.Consensus.Rules.PowConsensusRuleEngine.RewindAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\Rules\PowConsensusRuleEngine.cs:line 57
           at Stratis.Bitcoin.Consensus.ConsensusManager.InitializeAsync(ChainedHeader chainTip) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 255
           at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 237
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<Initialize>b__4_1(IFullNodeFeature feature) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 64
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 138'
[error] Stratis.Bitcoin.Builder.FullNodeFeatureExecutor
        An error occurred starting the application: System.AggregateException: One or more errors occurred. (No rewind data found for block `310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679`)
         ---> System.InvalidOperationException: No rewind data found for block `310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679`
           at Stratis.Bitcoin.Features.Consensus.CoinViews.LevelDbCoindb.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\Coindb\LeveldbCoindb.cs:line 202
           at Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\CachedCoinView.cs:line 622
           at Stratis.Bitcoin.Features.Consensus.Rules.PowConsensusRuleEngine.RewindAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\Rules\PowConsensusRuleEngine.cs:line 57
           at Stratis.Bitcoin.Consensus.ConsensusManager.InitializeAsync(ChainedHeader chainTip) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 255
           at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 237
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<Initialize>b__4_1(IFullNodeFeature feature) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 64
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 138
           --- End of inner exception stack trace ---
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 159
           at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 60
There was a problem initializing the node. Details: 'System.AggregateException: One or more errors occurred. (No rewind data found for block `310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679`)
 ---> System.InvalidOperationException: No rewind data found for block `310983-000000000000000029be5dfc455f9c82735fdf78ba4e31e2c591f424b83cf679`
   at Stratis.Bitcoin.Features.Consensus.CoinViews.LevelDbCoindb.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\Coindb\LeveldbCoindb.cs:line 202
   at Stratis.Bitcoin.Features.Consensus.CoinViews.CachedCoinView.Rewind() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\CoinViews\CachedCoinView.cs:line 622
   at Stratis.Bitcoin.Features.Consensus.Rules.PowConsensusRuleEngine.RewindAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin.Features.Consensus\Rules\PowConsensusRuleEngine.cs:line 57
   at Stratis.Bitcoin.Consensus.ConsensusManager.InitializeAsync(ChainedHeader chainTip) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Consensus\ConsensusManager.cs:line 255
   at Stratis.Bitcoin.Base.BaseFeature.InitializeAsync() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Base\BaseFeature.cs:line 237
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<Initialize>b__4_1(IFullNodeFeature feature) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 64
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 138
   --- End of inner exception stack trace ---
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean disposing) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 159
   at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Builder\FullNodeFeatureExecutor.cs:line 60
   at Stratis.Bitcoin.FullNode.Start() in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\FullNode.cs:line 227
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node, CancellationToken cancellationToken) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 90
   at Stratis.Bitcoin.Utilities.FullNodeExtensions.RunAsync(IFullNode node) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.Bitcoin\Utilities\FullNodeExtensions.cs:line 54
   at Stratis.BitcoinD.Program.Main(String[] args) in C:\Users\randalstout\source\repos\StratisFullNode\src\Stratis.BitcoinD\Program.cs:line 40'
Application is shutting down...
The CancellationTokenSource has been disposed.

Can't restart Stratis.BitcoinD...

**Comment by randalstout** [comment]
The solution given to me in Discord was to remove the AppData directory and restart the program.  However this means a total download of the blockchain each time this type of error happens.  Is there a more graceful way to fix this?
